// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0hknqT6UGGhXtCXv3JQeRR2Vbr9Y7_PI',
    appId: '1:941606226973:web:5751f97dd3effc6b09caf4',
    messagingSenderId: '941606226973',
    projectId: 'my-ecommerce-app-a0ac4',
    authDomain: 'my-ecommerce-app-a0ac4.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-a0ac4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjGEiOIROu7pbZg09E1gYg5E6Li5tLM7Y',
    appId: '1:941606226973:android:109897b91a99b1cf09caf4',
    messagingSenderId: '941606226973',
    projectId: 'my-ecommerce-app-a0ac4',
    storageBucket: 'my-ecommerce-app-a0ac4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG_R741Mpm-m-nSV_MCg6eHX4SBdtrfoM',
    appId: '1:941606226973:ios:da897882bc6ef40609caf4',
    messagingSenderId: '941606226973',
    projectId: 'my-ecommerce-app-a0ac4',
    storageBucket: 'my-ecommerce-app-a0ac4.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG_R741Mpm-m-nSV_MCg6eHX4SBdtrfoM',
    appId: '1:941606226973:ios:da897882bc6ef40609caf4',
    messagingSenderId: '941606226973',
    projectId: 'my-ecommerce-app-a0ac4',
    storageBucket: 'my-ecommerce-app-a0ac4.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0hknqT6UGGhXtCXv3JQeRR2Vbr9Y7_PI',
    appId: '1:941606226973:web:85f27f9e18bb433309caf4',
    messagingSenderId: '941606226973',
    projectId: 'my-ecommerce-app-a0ac4',
    authDomain: 'my-ecommerce-app-a0ac4.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-a0ac4.firebasestorage.app',
  );

}